// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from analytics.djinni

#import <Foundation/Foundation.h>


@interface SCKAnalyticsReporter : NSObject

+ (void)configure:(nonnull NSString *)trackerId;

+ (void)event:(nonnull NSString *)category
       action:(nonnull NSString *)action
        label:(nonnull NSString *)label;

+ (void)screenView:(nonnull NSString *)name;

+ (void)exception:(nonnull NSString *)description
          isFatal:(BOOL)isFatal;

+ (void)session:(BOOL)start;

@end
