// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from crash.djinni

#import <Foundation/Foundation.h>
@protocol SCKCrashHandler;


/** internal - do not use */
@protocol SCKBreakpad

- (void)start;

- (void)stop;

- (void)setUploadUrl;

- (void)setHandler:(nullable id<SCKCrashHandler>)hander;

@end
