// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from crash.djinni

#import <Foundation/Foundation.h>


/** internal - do not use */
@protocol SCKCrashHandler

- (void)header:(nonnull NSString *)path
           url:(nonnull NSString *)url;

@end
