// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>

/** (internal) */
typedef NS_ENUM(NSInteger, SCKDeviceOrientation)
{
    SCKDeviceOrientationUnknown,
    SCKDeviceOrientationPortrait,
    SCKDeviceOrientationProtraitDown,
    SCKDeviceOrientationLandscapeLeft,
    SCKDeviceOrientationLandscapeRight,
    SCKDeviceOrientationFaceup,
    SCKDeviceOrientationFacedown,
};
