// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import "SCKDeviceOrientation.h"
#import <Foundation/Foundation.h>


/** (internal) */
@protocol SCKDevice

- (SCKDeviceOrientation)getOrientation;

- (nonnull NSString *)getID;

- (nonnull NSString *)getDeviceOs;

- (nonnull NSString *)getDeviceOsVersion;

- (nonnull NSString *)getDeviceOsApiVersion;

- (nonnull NSString *)getDevicePlatform;

- (nonnull NSString *)getDeviceBrand;

- (nonnull NSString *)getDeviceManufacturer;

- (nonnull NSString *)getDeviceModel;

- (nonnull NSString *)getUserAgent;

@end
