// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from threading.djinni

#import <Foundation/Foundation.h>


/** internal - do not use */
@interface SCKExecutable : NSObject

- (void)run;

@end
