// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class SCKScapeSession;
@protocol SCKDebugSession;
@protocol SCKDevice;
@protocol SCKExecutorService;
@protocol SCKLocationSession;
@protocol SCKMotionSession;
@protocol SCKPlatformUtility;


/**
 * (internal)
 * global static object managing the C++ side access of platform-based instances
 */
@interface SCKInstanceManager : NSObject

/** (internal) */
+ (nullable SCKScapeSession *)getScapeSession;

+ (void)setScapeSession:(nullable SCKScapeSession *)session;

/** (internal) */
+ (nullable id<SCKLocationSession>)getLocationSession;

+ (void)setLocationSession:(nullable id<SCKLocationSession>)session;

/** (internal) */
+ (nullable id<SCKMotionSession>)getMotionSession;

+ (void)setMotionSession:(nullable id<SCKMotionSession>)session;

/** (internal) */
+ (nullable id<SCKDebugSession>)getDebugSession;

+ (void)setDebugSession:(nullable id<SCKDebugSession>)session;

/** (internal) */
+ (nullable id<SCKExecutorService>)getScapeExecutorService;

+ (void)setScapeExecutorService:(nullable id<SCKExecutorService>)executor;

/** (internal) */
+ (nullable id<SCKExecutorService>)getAnalyticsExecutorService;

+ (void)setAnalyticsExecutorService:(nullable id<SCKExecutorService>)executor;

/** (internal) */
+ (nullable id<SCKPlatformUtility>)getPlatformUtility;

+ (void)setPlatformUtility:(nullable id<SCKPlatformUtility>)platform;

/** (internal) */
+ (nullable id<SCKDevice>)getDevice;

+ (void)setDevice:(nullable id<SCKDevice>)device;

/** (internal) */
+ (nonnull NSString *)getSdkVersion;

+ (void)setSdkVersion:(nonnull NSString *)version;

/** (internal) */
+ (void)terminate;

@end
