// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from location.djinni

#import "SCKLocationMeasurements.h"
#import <Foundation/Foundation.h>
@protocol SCKLocationSession;


/**
 * (internal)
 * Observer for all location session related callbacks
 */
@protocol SCKLocationSessionObserver

- (void)onLocationSessionStarted:(nullable id<SCKLocationSession>)session;

- (void)onLocationSessionError:(nullable id<SCKLocationSession>)session
                       message:(nonnull NSString *)message;

- (void)onLocationSessionClosed:(nullable id<SCKLocationSession>)session;

- (void)onLocationRawEstimated:(nullable id<SCKLocationSession>)session
                  measurements:(nonnull SCKLocationMeasurements *)measurements;

@end
