// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from location.djinni

#import <Foundation/Foundation.h>

/**
 * (public)
 * Representing geolocation lat_lng
 */
@interface SCKLatLng : NSObject
- (nonnull instancetype)initWithLatitude:(double)latitude
                               longitude:(double)longitude;
+ (nonnull instancetype)latLngWithLatitude:(double)latitude
                                 longitude:(double)longitude;

@property (nonatomic, readonly) double latitude;

@property (nonatomic, readonly) double longitude;

@end
