// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#import "SCKLogLevel.h"
#import "SCKLogOutput.h"
#import <Foundation/Foundation.h>


@interface SCKLogConfig : NSObject

+ (void)setLevel:(SCKLogLevel)logLevel;

+ (void)setOutput:(SCKLogOutput)logOutput;

@end
