// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#import "SCKLogLevel.h"
#import <Foundation/Foundation.h>


@interface SCKLog : NSObject

+ (void)log:(SCKLogLevel)logLevel
        tag:(nonnull NSString *)tag
        msg:(nonnull NSString *)msg;

@end
