// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#import <Foundation/Foundation.h>

/** (internal) */
typedef NS_OPTIONS(NSUInteger, SCKLogOutput)
{
    SCKLogOutputNoOuput = 0,
    SCKLogOutputConsole = 1 << 0,
    SCKLogOutputFile = 1 << 1,
    SCKLogOutputOverlay = 1 << 2,
    SCKLogOutputNetwork = 1 << 3,
    SCKLogOutputAllOuput = 0 | SCKLogOutputConsole | SCKLogOutputFile | SCKLogOutputOverlay | SCKLogOutputNetwork,
};
