// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from location.djinni

#import "SCKLocationMeasurements.h"
#import <Foundation/Foundation.h>
@protocol SCKLocationSessionObserver;


/**
 * (internal)
 * Allows getting GPS (global positioning system) and compass values
 */
@protocol SCKLocationSession

/**
 * (internal)
 * Start GPS fetching at continuous interval (Mandatory to call before calling getLastLocation())
 */
- (void)startFetch;

/**
 * (internal)
 * Stop GPS fetching
 */
- (void)stopFetch;

/**
 * (internal)
 * Get the last known GPS location
 * Note: have to call startFetch before
 */
- (nullable SCKLocationMeasurements *)getLastLocation;

/**
 * (internal)
 * Retrieve the current callback observer for the current session
 */
- (nullable id<SCKLocationSessionObserver>)getLocationSessionObserver;

/**
 * (internal)
 * Set the current callback observer for the current session
 */
- (void)setLocationSessionObserver:(nullable id<SCKLocationSessionObserver>)observer;

@end
