// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import "SCKLocationMeasurements.h"
#import "SCKMotionMeasurements.h"
#import "SCKScapeMeasurements.h"
#import <Foundation/Foundation.h>

/**
 * (public) -
 * Raw measurements read from device's sensors (gyroscope, accelerometer, gps, magnetometer) and Scape Vision Engine.
 */
@interface SCKMeasurements : NSObject
- (nonnull instancetype)initWithDeviceLocationMeasurements:(nonnull SCKLocationMeasurements *)deviceLocationMeasurements
                                  deviceMotionMeasurements:(nonnull SCKMotionMeasurements *)deviceMotionMeasurements
                                         scapeMeasurements:(nonnull SCKScapeMeasurements *)scapeMeasurements;
+ (nonnull instancetype)measurementsWithDeviceLocationMeasurements:(nonnull SCKLocationMeasurements *)deviceLocationMeasurements
                                          deviceMotionMeasurements:(nonnull SCKMotionMeasurements *)deviceMotionMeasurements
                                                 scapeMeasurements:(nonnull SCKScapeMeasurements *)scapeMeasurements;

/** Device's location-related measurements */
@property (nonatomic, readonly, nonnull) SCKLocationMeasurements * deviceLocationMeasurements;

/** Device's motion-related measurements */
@property (nonatomic, readonly, nonnull) SCKMotionMeasurements * deviceMotionMeasurements;

/** Scape-related measurements */
@property (nonatomic, readonly, nonnull) SCKScapeMeasurements * scapeMeasurements;

@end
