// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from motion.djinni

#import "SCKMotionMeasurements.h"
#import <Foundation/Foundation.h>
@protocol SCKMotionSessionObserver;


/**
 * (internal)
 * Allows getting motion (accelerometer, gyroscope, pedometer, magnetometer, barometer) values
 */
@protocol SCKMotionSession

/**
 * (internal)
 * Start motion fetching at continuous interval (Mandatory to call before calling getLastMotion())
 */
- (void)startFetch;

/**
 * (internal)
 * Stop motion fetching	
 */
- (void)stopFetch;

/**
 * (internal)
 * Get the latest known motion values
 */
- (nullable SCKMotionMeasurements *)getLastMotion;

/**
 * (internal)
 * Retrieve the current callback observer for the current session
 */
- (nullable id<SCKMotionSessionObserver>)getMotionSessionObserver;

/**
 * (internal)
 * Set the current callback observer for the current session
 */
- (void)setMotionSessionObserver:(nullable id<SCKMotionSessionObserver>)observer;

@end
