// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from motion.djinni

#import "SCKMotionMeasurements.h"
#import <Foundation/Foundation.h>
@protocol SCKMotionSession;


/**
 * (internal)
 * Observer for all motion session related callbacks
 */
@protocol SCKMotionSessionObserver

- (void)onMotionSessionStarted:(nullable id<SCKMotionSession>)session;

- (void)onMotionSessionError:(nullable id<SCKMotionSession>)session
                     message:(nonnull NSString *)message;

- (void)onMotionSessionClosed:(nullable id<SCKMotionSession>)session;

- (void)onMotionRawEstimated:(nullable id<SCKMotionSession>)session
                measurements:(nonnull SCKMotionMeasurements *)measurements;

@end
