// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import <Foundation/Foundation.h>

/** internal - do not use */
@interface SCKNetworkHeaders : NSObject
- (nonnull instancetype)initWithHeaders:(nonnull NSDictionary<NSString *, NSString *> *)headers;
+ (nonnull instancetype)networkHeadersWithHeaders:(nonnull NSDictionary<NSString *, NSString *> *)headers;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * headers;

@end
