// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import <Foundation/Foundation.h>

/** internal - do not use */
@interface SCKNetworkBody : NSObject
- (nonnull instancetype)initWithBody:(nonnull NSString *)body;
+ (nonnull instancetype)networkBodyWithBody:(nonnull NSString *)body;

@property (nonatomic, readonly, nonnull) NSString * body;

@end
