// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "SCKNetworkResponse.h"
#import <Foundation/Foundation.h>


/** internal - do not use */
@protocol SCKNetworkListener

- (void)success:(nonnull SCKNetworkResponse *)response;

- (void)failure:(nonnull SCKNetworkResponse *)response;

@end
