// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import <Foundation/Foundation.h>

/** internal - do not use */
@interface SCKNetworkResponse : NSObject
- (nonnull instancetype)initWithCode:(int64_t)code
                              result:(nonnull NSString *)result;
+ (nonnull instancetype)networkResponseWithCode:(int64_t)code
                                         result:(nonnull NSString *)result;

@property (nonatomic, readonly) int64_t code;

@property (nonatomic, readonly, nonnull) NSString * result;

@end
