// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import "SCKLogLevel.h"
#import <Foundation/Foundation.h>
@class SCKExecutable;
@protocol SCKTimer;
@protocol SCKVideoFrame;


/** (internal) */
@protocol SCKPlatformUtility

/** (internal) */
- (void)runOnUIThread:(nullable SCKExecutable *)executable;

- (nullable id<SCKTimer>)createTimer:(BOOL)repeated
                            interval:(int64_t)interval;

/** (internal) */
- (int64_t)getSystemTickNano;

- (int64_t)getSystemTickMsec;

- (double)getSystemTickSec;

- (void)endEditing:(BOOL)force;

- (void)setEnvironmentVar:(nonnull NSString *)name
                    value:(nonnull NSString *)value
                overwrite:(BOOL)overwrite;

- (nonnull NSString *)createUUID;

/** (internal) */
- (nonnull NSString *)getHomeDirectory;

- (nonnull NSString *)getPackFilePath:(nonnull NSString *)file;

- (nonnull NSString *)getPackFileBuffer:(nonnull NSString *)file;

/**copy pack file to home directory and return path in home directory */
- (nonnull NSString *)getPackFileToHomePath:(nonnull NSString *)file;

- (nonnull NSSet<NSString *> *)getFilesFromPathBySuffix:(nonnull NSString *)path
                                                 suffix:(nonnull NSString *)suffix;

- (nonnull NSString *)getSubDirInHome:(nonnull NSString *)subDir;

- (nonnull NSString *)getFileNameFromPath:(nonnull NSString *)path;

- (BOOL)fileExists:(nonnull NSString *)pathName;

- (BOOL)deleteFile:(nonnull NSString *)fullpath;

/** (internal) */
- (nullable id<SCKVideoFrame>)createVideoFrame;

/** (internal) */
- (void)overlay:(SCKLogLevel)level
            tag:(nonnull NSString *)tag
        message:(nonnull NSString *)message;

- (void)clearOverlay;

@end
