// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import <Foundation/Foundation.h>

/**
 * (public) -
 * Current session state
 */
typedef NS_ENUM(NSInteger, SCKScapeSessionState)
{
    /** No current error to report */
    SCKScapeSessionStateNoError,
    /** Locations sensors (compass, gps) error  */
    SCKScapeSessionStateLocationSensorsError,
    /** Motion sensors (gyro, magnetometer) error */
    SCKScapeSessionStateMotionSensorsError,
    /** image sensors (ar image read) error */
    SCKScapeSessionStateImageSensorsError,
    /** Locking position and orientation error */
    SCKScapeSessionStateLockingPositionError,
    /** Authentication error (api key) */
    SCKScapeSessionStateAuthenticationError,
    /** Network error */
    SCKScapeSessionStateNetworkError,
    /** Fetching measurements resulted in an unexpected error */
    SCKScapeSessionStateUnexpectedError,
};
