// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import <Foundation/Foundation.h>


/**
 * (internal)
 * Utils class: allows conversion between WGS coordinates to local as well as computing the distance
 * between coordinates
 */
@interface SCKScapeUtils : NSObject

+ (double)metersBetweenCoordinates:(double)latitude1
                        longitude1:(double)longitude1
                         latitude2:(double)latitude2
                        longitude2:(double)longitude2;

+ (double)angleBetweenCoordinates:(double)latitude1
                       longitude1:(double)longitude1
                        latitude2:(double)latitude2
                       longitude2:(double)longitude2;

+ (nonnull NSArray<NSNumber *> *)wgsToLocal:(double)latitude
                                  longitude:(double)longitude
                                   altitude:(double)altitude
                                     cellId:(int64_t)cellId;

+ (nonnull NSArray<NSNumber *> *)localToWgs:(double)x
                                          y:(double)y
                                          z:(double)z
                                     cellId:(int64_t)cellId;

+ (int64_t)cellIdForWgs:(double)latitude
              longitude:(double)longitude;

@end
