// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import <Foundation/Foundation.h>
@class SCKScapeSession;


/**
 * (internal) -
 * Create instance of ScapeSession
 */
@interface SCKScapeSessionFactory : NSObject

/**
 * (internal)
 * Create ScapeKit session
 */
+ (nullable SCKScapeSession *)create:(nonnull NSString *)apiKey;

@end
