// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class SCKExecutable;
@protocol SCKTimer;


/** (internal) */
@protocol SCKTimer

- (void)start;

- (void)stop;

- (void)pause;

- (void)resume;

- (nullable id<SCKTimer>)setExecutable:(nullable SCKExecutable *)executable;

- (nullable SCKExecutable *)getExecutable;

- (int64_t)getInterval;

- (int64_t)getTimePassed;

- (BOOL)isStarted;

@end
