// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import <Foundation/Foundation.h>
@class SCKTestManager;


/** internal - do not use */
@interface SCKTestManager : NSObject

+ (nullable SCKTestManager *)instance;

- (BOOL)initialize:(nonnull NSString *)selfPath;

- (int32_t)runTests;

@end
