// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import <Foundation/Foundation.h>

/** (public) */
typedef NS_ENUM(NSInteger, SCKXrTrackingState)
{
    SCKXrTrackingStatePaused,
    SCKXrTrackingStateStopped,
    SCKXrTrackingStateTracking,
};
