// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import <Foundation/Foundation.h>

@interface SCKXrPointCloud : NSObject
- (nonnull instancetype)initWithId:(nonnull NSArray<NSNumber *> *)id
                            points:(nonnull NSArray<NSNumber *> *)points;
+ (nonnull instancetype)xrPointCloudWithId:(nonnull NSArray<NSNumber *> *)id
                                    points:(nonnull NSArray<NSNumber *> *)points;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * id;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * points;

@end
