// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import "SCKXrEulerAngles.h"
#import "SCKXrTrackingState.h"
#import <Foundation/Foundation.h>

/** (public) */
@interface SCKXrCamera : NSObject
- (nonnull instancetype)initWithTransform:(nonnull NSArray<NSNumber *> *)transform
                               viewMatrix:(nonnull NSArray<NSNumber *> *)viewMatrix
                         projectionMatrix:(nonnull NSArray<NSNumber *> *)projectionMatrix
                              eulerAngles:(nonnull SCKXrEulerAngles *)eulerAngles
                            trackingState:(SCKXrTrackingState)trackingState
                              focalLength:(nonnull NSArray<NSNumber *> *)focalLength
                           principalPoint:(nonnull NSArray<NSNumber *> *)principalPoint;
+ (nonnull instancetype)xrCameraWithTransform:(nonnull NSArray<NSNumber *> *)transform
                                   viewMatrix:(nonnull NSArray<NSNumber *> *)viewMatrix
                             projectionMatrix:(nonnull NSArray<NSNumber *> *)projectionMatrix
                                  eulerAngles:(nonnull SCKXrEulerAngles *)eulerAngles
                                trackingState:(SCKXrTrackingState)trackingState
                                  focalLength:(nonnull NSArray<NSNumber *> *)focalLength
                               principalPoint:(nonnull NSArray<NSNumber *> *)principalPoint;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * transform;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * viewMatrix;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * projectionMatrix;

@property (nonatomic, readonly, nonnull) SCKXrEulerAngles * eulerAngles;

@property (nonatomic, readonly) SCKXrTrackingState trackingState;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * focalLength;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * principalPoint;

@end
