// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import <Foundation/Foundation.h>

/** (public) */
@interface SCKXrLight : NSObject
- (nonnull instancetype)initWithAmbientIntensity:(double)ambientIntensity
                         ambientColorTemperature:(double)ambientColorTemperature;
+ (nonnull instancetype)xrLightWithAmbientIntensity:(double)ambientIntensity
                            ambientColorTemperature:(double)ambientColorTemperature;

@property (nonatomic, readonly) double ambientIntensity;

@property (nonatomic, readonly) double ambientColorTemperature;

@end
