// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import "SCKXrAlignment.h"
#import "SCKXrCenter.h"
#import "SCKXrExtent.h"
#import "SCKXrNode.h"
#import <Foundation/Foundation.h>

/** (public) */
@interface SCKXrPlane : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                         alignment:(SCKXrAlignment)alignment
                              node:(nonnull SCKXrNode *)node
                            center:(nonnull SCKXrCenter *)center
                            extent:(nonnull SCKXrExtent *)extent;
+ (nonnull instancetype)xrPlaneWithId:(nonnull NSString *)id
                            alignment:(SCKXrAlignment)alignment
                                 node:(nonnull SCKXrNode *)node
                               center:(nonnull SCKXrCenter *)center
                               extent:(nonnull SCKXrExtent *)extent;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly) SCKXrAlignment alignment;

@property (nonatomic, readonly, nonnull) SCKXrNode * node;

@property (nonatomic, readonly, nonnull) SCKXrCenter * center;

@property (nonatomic, readonly, nonnull) SCKXrExtent * extent;

@end
