// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import "SCKXrAnchor.h"
#import "SCKXrCamera.h"
#import "SCKXrLight.h"
#import "SCKXrPointCloud.h"
#import <Foundation/Foundation.h>
@protocol SCKVideoFrame;

/** (public) */
@interface SCKXrFrame : NSObject
- (nonnull instancetype)initWithVideoFrame:(nullable id<SCKVideoFrame>)videoFrame
                                    camera:(nonnull SCKXrCamera *)camera
                             lightEstimate:(nonnull SCKXrLight *)lightEstimate
                                   anchors:(nonnull NSArray<SCKXrAnchor *> *)anchors
                          rawFeaturePoints:(nonnull SCKXrPointCloud *)rawFeaturePoints;
+ (nonnull instancetype)xrFrameWithVideoFrame:(nullable id<SCKVideoFrame>)videoFrame
                                       camera:(nonnull SCKXrCamera *)camera
                                lightEstimate:(nonnull SCKXrLight *)lightEstimate
                                      anchors:(nonnull NSArray<SCKXrAnchor *> *)anchors
                             rawFeaturePoints:(nonnull SCKXrPointCloud *)rawFeaturePoints;

@property (nonatomic, readonly, nullable) id<SCKVideoFrame> videoFrame;

@property (nonatomic, readonly, nonnull) SCKXrCamera * camera;

@property (nonatomic, readonly, nonnull) SCKXrLight * lightEstimate;

@property (nonatomic, readonly, nonnull) NSArray<SCKXrAnchor *> * anchors;

@property (nonatomic, readonly, nonnull) SCKXrPointCloud * rawFeaturePoints;

@end
