// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from xr.djinni

#import "SCKXrFrame.h"
#import "SCKXrWorldAlignment.h"
#import <Foundation/Foundation.h>
@protocol SCKXrSessionObserver;


/**
 * (public)
 * Simple abstraction layer sitting on top of ARKit/ARCore: 
 * allows using XR related features (camera pose, plane detection, world alignment) easily
 */
@protocol SCKXrSession

/** (public) */
- (void)startTracking:(nullable id<SCKXrSessionObserver>)observer;

/** (public) */
- (void)stopTracking;

/** (public) */
- (void)resetTracking:(nullable id<SCKXrSessionObserver>)observer;

/** (public) */
- (void)setWorldAlignment:(SCKXrWorldAlignment)alignment;

/** (public) */
- (void)setPlaneDetection:(BOOL)detection;

/** (public) */
- (void)setDebugMode:(BOOL)debug;

/** (public) */
- (void)setLightEstimation:(BOOL)estimation;

/** (public) */
- (BOOL)isPlaneDetection;

/** (public) */
- (BOOL)isDebugMode;

/** (public) */
- (BOOL)isLightEstimation;

/** (public) */
- (SCKXrWorldAlignment)getWorldAlignment;

/** (public) */
- (nullable SCKXrFrame *)getLastFrame;

@end
